// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zytuqmzcinpegiivcanb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5dHVxbXpjaW5wZWdpaXZjYW5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzk5MTUsImV4cCI6MjA2OTk1NTkxNX0.Jf13V2iWjBeaTAu3fbM5NJldfpGogvVQKK5hoIB-kX0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});